### ISSUE TITLE
Cant parse man shrugging 🤷‍♂

### ISSUE THREAD

**Issue by omaijdot** [wooorm/retext-emoji#16]
I tried used retect-emoji and gemoji to take parsing the unicode  to shortcode. unfortunately for the 2 unicode like man_shrugging or woman_student. it is failed to load properly. please refer to imaage attached. May i know how to deal with 2 unicode to parse as 1 emoji?
![image](https://user-images.githubusercontent.com/1439453/30793557-6ffcc30e-a1f5-11e7-9457-63c387d73fa4.png)

**Comment by wooorm** [comment]
Hi @omaijdot! I’m sorry about this, and thanks for the images! It’s the same issue as GH-15 though, so I’ll keep that open and close this here.
